name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2sdk-ports:latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        apk add build-base git

    - name: Install ps2stuff
      run: |
        git clone https://github.com/ps2dev/ps2stuff.git
        cd ps2stuff && make clean all install

    - name: Compile project
      run: |
        make clean all install

    - name: Compile GLUT
      run: |
        cd glut && make clean all install
    
    - name: Compile examples
      run: |
        cd examples
        # For now just box example is compiling
        cd box && make clean all

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: examples
        path: |
          examples/box/box.elf
