name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2sdk-ports:latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        apk add build-base git

    - name: Install ps2stuff
      run: |
        git clone https://github.com/ps2dev/ps2stuff.git
        cd ps2stuff 
        make -j $(getconf _NPROCESSORS_ONLN) clean
        make -j $(getconf _NPROCESSORS_ONLN) all
        make -j $(getconf _NPROCESSORS_ONLN) install

    - name: Compile project
      run: |
        make -j $(getconf _NPROCESSORS_ONLN) clean
        make -j $(getconf _NPROCESSORS_ONLN) all
        make -j $(getconf _NPROCESSORS_ONLN) install

    - name: Compile GLUT
      run: |
        cd glut 
        make -j $(getconf _NPROCESSORS_ONLN) clean
        make -j $(getconf _NPROCESSORS_ONLN) all
        make -j $(getconf _NPROCESSORS_ONLN) install
    
    - name: Compile examples
      run: |
        cd examples
        # For now just box, logo and nehe examples are compiling
        cd box && make clean all && cd ..
        cd logo && make clean all && cd ..
        cd nehe/lesson02 && make clean all && cd ../..
        cd nehe/lesson03 && make clean all && cd ../..
        cd nehe/lesson04 && make clean all && cd ../..
        cd nehe/lesson05 && make clean all && cd ../..


    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: examples
        path: |
          examples/**/*.elf
          examples/**/*.gl
          examples/**/*.rtx
